from collections.abc import Callable


class RmlEvent:
    def type(self) -> str: ...

    def target(self) -> object: ...

    def current_target(self) -> object: ...

    def stop_propagation(self) -> None: ...

    def get_parameter(self, key: str, default_val: str = '') -> str: ...

class RmlElement:
    def get_element_by_id(self, arg: str, /) -> object: ...

    def query_selector_all(self, arg: str, /) -> list: ...

    def query_selector(self, arg: str, /) -> object: ...

    def parent(self) -> object: ...

    def children(self) -> list: ...

    def num_children(self) -> int: ...

    def append_child(self, tag_name: str) -> object: ...

    def remove_child(self, arg: RmlElement, /) -> None: ...

    def set_inner_rml(self, arg: str, /) -> None: ...

    def get_inner_rml(self) -> str: ...

    def set_attribute(self, arg0: str, arg1: str, /) -> None: ...

    def get_attribute(self, name: str, default_val: str = '') -> str: ...

    def has_attribute(self, arg: str, /) -> bool: ...

    def remove_attribute(self, arg: str, /) -> None: ...

    def set_class(self, arg0: str, arg1: bool, /) -> None: ...

    def is_class_set(self, arg: str, /) -> bool: ...

    def set_class_names(self, arg: str, /) -> None: ...

    def get_class_names(self) -> str: ...

    def set_property(self, arg0: str, arg1: str, /) -> bool: ...

    def remove_property(self, arg: str, /) -> None: ...

    def add_event_listener(self, arg0: str, arg1: Callable, /) -> None: ...

    @property
    def id(self) -> str: ...

    @id.setter
    def id(self, arg: str, /) -> None: ...

    @property
    def tag_name(self) -> str: ...

    @property
    def scroll_left(self) -> float: ...

    @scroll_left.setter
    def scroll_left(self, arg: float, /) -> None: ...

    @property
    def scroll_top(self) -> float: ...

    @scroll_top.setter
    def scroll_top(self, arg: float, /) -> None: ...

    @property
    def scroll_width(self) -> float: ...

    @property
    def scroll_height(self) -> float: ...

    def scroll_into_view(self, align_top: bool = True) -> None: ...

    def focus(self) -> bool: ...

    def blur(self) -> None: ...

class RmlDocument(RmlElement):
    def create_element(self, arg: str, /) -> object: ...

    def create_text_node(self, arg: str, /) -> object: ...

    def show(self) -> None: ...

    def hide(self) -> None: ...

    @property
    def title(self) -> str: ...

    @title.setter
    def title(self, arg: str, /) -> None: ...

def get_document(arg: str, /) -> object: ...
